.PHONY: clean All

All:
	@echo "==========Building project:[ project2 - Debug ]=========="
	@cd "project2" && "$(MAKE)" -f  "project2.mk"
clean:
	@echo "==========Cleaning project:[ project2 - Debug ]----------"
	@cd "project2" && "$(MAKE)" -f  "project2.mk" clean
